### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by kta25298** [weiffert/Component-Based-Game-Engine#10]
line 94 in Game.cpp causes it to break. BaseState's update function has no definition, and I don't know what its supposed to do or how its supposed to work

**Comment by weiffert** [comment]
Ok. My understanding of the question is that BaseState's update is a pure virtual. Check and make sure that the state pointer in pointing to a class that is derived from BaseState. If that does not solve the problem, check and make sure that the function signature is correct. If that still doesn't solve it, I will need to take a closer look.
