### ISSUE TITLE
BaseController

### ISSUE THREAD

**Issue by weiffert** [weiffert/Component-Based-Game-Engine#3]
If we have a vector of required properties and try to have them self attaching, we need to have a setRequiredProperties function. If we have extra time, lets add this and use the self attaching method. Otherwise, I don't think it is needed. Opinions?

**Comment by kta25298** [comment]
That sounds managible. On paper at least. I say we might as well try it.

**Comment by weiffert** [comment]
I added a control function. That encapsulates the purpose of the controller. I don't know the best way to change how this function is used though. There is virtual functions and base classes, but that seems messy. All that would be changed is control(). Ideas?
